[build]
  functions = "netlify/functions"

[build.environment]
  FIREBASE_API_KEY = "your-api-key"
  FIREBASE_AUTH_DOMAIN = "your-auth-domain"
  FIREBASE_PROJECT_ID = "your-project-id"
  FIREBASE_STORAGE_BUCKET = "your-storage-bucket"
  FIREBASE_MESSAGING_SENDER_ID = "your-messaging-sender-id"
  FIREBASE_APP_ID = "your-app-id"
  FIREBASE_MEASUREMENT_ID = "your-measurement-id"
  FIREBASE_SERVICE_ACCOUNT = '{"type":"service_account","project_id":"your-project-id", ...}'
